#!/bin/bash

usage() {
  echo "Usage: $0 [ -j ] For JSON output"
  echo "Usage: $0 [ -c ] For CSV output"
  echo "Usage: $@ [ -e ENV ]"
  echo "Usage: $@ [ -s SERIAL ]" 
  echo "Usage: $@ [ -p PATIENT_ID ]"
  echo "Usage: $0 [ --time1 <initial timestamp> --time2 <final timestamp> ]"

  1>&2; exit 1;
}

exit_abnormal() {
  exit 1
}

while getopts "hcje:s:p:t:-:" options; do

	case "${options}" in

	h)
		usage
		;;
	c)
		FORMAT="csv[separator=', '](timestamp,textPayload)"
		;;
	j)
		FORMAT=json
		;;
	e)
		ENV=${OPTARG}
		gcloud config set project swordhealth-production-$ENV
		;;
	t)
		DATE1=${OPTARG}
		;;
	-)

	case "${OPTARG}" in
                time1)
			val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
			DATE1=${val}
			;;
                time2)
			val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
			DATE2=${val}
			;;
                *)
			;;
        esac
        ;;

	s)
		SERIAL=${OPTARG}
		FILTER='projects/swordhealth-production-'$ENV'/logs/mobile_log labels.serial="'$SERIAL'" AND timestamp>="'$DATE1'T00:00:00Z"'
		if ! [ -n "$DATE2" ]; then
			DATE2=$(date +%Y-%m-%dT%H:%M:%S.000Z)
		fi
		MESSAGE="${FILTER} AND timestamp<=\"$DATE2\""
		echo "query: $MESSAGE"
		if [ $FORMAT == "json" ]; then
			gcloud logging read --format=$FORMAT "${MESSAGE}" > $ENV-$SERIAL.json
		else
			gcloud logging read --format="${FORMAT}" "${MESSAGE}" > $ENV-$SERIAL.csv
		fi
		;;

	p)
		PATIENT=${OPTARG}
		FILTER='projects/swordhealth-production-'$ENV'/logs/mobile_log labels.patient_id="'$PATIENT'" AND timestamp>="'$DATE1'T00:00:00Z"'
		if ! [ -n "$DATE2" ]; then
			DATE2=$(date +%Y-%m-%dT%H:%M:%S.000Z)
		fi
		MESSAGE="${FILTER} AND timestamp<=\"$DATE2\""
		echo "query: $MESSAGE"
		if [[ $FORMAT == "json" ]]; then
			gcloud logging read --format=$FORMAT "${MESSAGE}" > $ENV-$PATIENT.json
		else
			gcloud logging read --format="${FORMAT}" "${MESSAGE}" > $ENV-$PATIENT.csv
		fi
		;;
	:)
		echo "Error: -${OPTARG} requires an argument."
		usage
		;;
	*)
		usage
		;;
	esac
done

exit 0
